#!/usr/bin/env python3
"""
Generate a JS manifest of all .lvl files for the level-viewer HTML tool.

Scans levels/ and complevels/ relative to the repo root and emits
target/diagnostics/level-viewer/levels-manifest.js, which assigns
window.LEVELS_MANIFEST to a list of {group, name, path, content} entries
so the static HTML can populate its sidebar without an HTTP server.

Run from anywhere inside the repo:

    python tools/level-viewer/generate_manifest.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import List, Dict


GROUPS = ("levels", "complevels")
OUT_REL = Path("target/diagnostics/level-viewer/levels-manifest.js")


def find_repo_root(start: Path) -> Path:
    current = start.resolve()
    for candidate in [current, *current.parents]:
        has_levels = (candidate / "levels").is_dir() or (candidate / "complevels").is_dir()
        has_project_marker = (candidate / "pom.xml").is_file() or (candidate / ".git").exists()
        if has_levels and has_project_marker:
            return candidate
    return current


def collect_levels(root: Path) -> List[Dict[str, str]]:
    entries: List[Dict[str, str]] = []
    for group in GROUPS:
        group_dir = root / group
        if not group_dir.is_dir():
            continue
        for lvl in sorted(group_dir.glob("*.lvl"), key=lambda p: p.name.lower()):
            try:
                text = lvl.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                text = lvl.read_text(encoding="latin-1")
            entries.append({
                "group": group,
                "name": lvl.stem,
                "path": f"{group}/{lvl.name}",
                "content": text,
            })
    return entries


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=None,
                        help="Repository root (auto-detected if omitted)")
    parser.add_argument("--out", type=Path, default=None,
                        help="Output JS file (defaults to target/diagnostics/level-viewer/levels-manifest.js)")
    args = parser.parse_args()

    root = args.root.resolve() if args.root else find_repo_root(Path(__file__).parent)
    out = args.out.resolve() if args.out else (root / OUT_REL)

    entries = collect_levels(root)
    out.parent.mkdir(parents=True, exist_ok=True)

    body = json.dumps(entries, ensure_ascii=False, indent=2)
    header = (
        "// Auto-generated by tools/level-viewer/generate_manifest.py\n"
        f"// Levels: {len(entries)} (run the script again after adding/removing .lvl files)\n"
    )
    out.write_text(f"{header}window.LEVELS_MANIFEST = {body};\n", encoding="utf-8")

    by_group = {g: sum(1 for e in entries if e["group"] == g) for g in GROUPS}
    print(f"Wrote {out.relative_to(root)} ({len(entries)} levels: " +
          ", ".join(f"{g}={by_group[g]}" for g in GROUPS) + ")")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
